UsernameInputBox = "name=username"
PasswordInputBox = "name=password"
LoginButton = "xpath=//button[@type='submit']"
LogoutButton="xpath=//a[contains(text(),'Logout')]"
MenuProfil="xpath=//span[@class='oxd-userdropdown-tab'] "
PimButton="xpath=//span[contains(@class,'oxd-main-menu-item--name') and text()='PIM']"
AddTitle="xpath=//h5[@class='oxd-text oxd-text--h5 oxd-table-filter-title']"
AddButtonTittle="xpath=//h5[@class='oxd-text oxd-text--h5 oxd-table-filter-title']"
AddButton="xpath=//button[normalize-space()='Add']"
EmployeeFirstName="name=firstName"
EmployeeLastName="name=lastName"
IdEmployee=" xpath=(//input[@class='oxd-input oxd-input--active'])[2]"
SubmitButton="css=button[type='submit']"
PersonalDetailsTittle="xpath=//h6[text()='Personal Details']"
EmpNationality="xpath://label[text()='Nationality']/ancestor::div[contains(@class, 'oxd-input-group')]//div[contains(@class, 'oxd-select-text')]"
EmpNationalityInput="xpath://*[text()"